// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: street.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Street struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreetName string `protobuf:"bytes,1,opt,name=street_name,json=streetName,proto3" json:"street_name,omitempty"`
	Town       string `protobuf:"bytes,2,opt,name=town,proto3" json:"town,omitempty"`
	City       string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country    string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *Street) Reset() {
	*x = Street{}
	if protoimpl.UnsafeEnabled {
		mi := &file_street_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Street) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Street) ProtoMessage() {}

func (x *Street) ProtoReflect() protoreflect.Message {
	mi := &file_street_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Street.ProtoReflect.Descriptor instead.
func (*Street) Descriptor() ([]byte, []int) {
	return file_street_proto_rawDescGZIP(), []int{0}
}

func (x *Street) GetStreetName() string {
	if x != nil {
		return x.StreetName
	}
	return ""
}

func (x *Street) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *Street) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Street) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_street_proto protoreflect.FileDescriptor

var file_street_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b,
	0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x65,
	0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x74, 0x72, 0x65, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f, 0x77,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x77, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x04, 0x5a, 0x02, 0x2e,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_street_proto_rawDescOnce sync.Once
	file_street_proto_rawDescData = file_street_proto_rawDesc
)

func file_street_proto_rawDescGZIP() []byte {
	file_street_proto_rawDescOnce.Do(func() {
		file_street_proto_rawDescData = protoimpl.X.CompressGZIP(file_street_proto_rawDescData)
	})
	return file_street_proto_rawDescData
}

var file_street_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_street_proto_goTypes = []interface{}{
	(*Street)(nil), // 0: Street
}
var file_street_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_street_proto_init() }
func file_street_proto_init() {
	if File_street_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_street_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Street); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_street_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_street_proto_goTypes,
		DependencyIndexes: file_street_proto_depIdxs,
		MessageInfos:      file_street_proto_msgTypes,
	}.Build()
	File_street_proto = out.File
	file_street_proto_rawDesc = nil
	file_street_proto_goTypes = nil
	file_street_proto_depIdxs = nil
}
